module.exports = {
    DB_DIR: null,
    DB: null,
    WEBDECK: null,
    Opens_windows: null,
    ProgramsExe: null,
    Server_port: null,
    List_macros: null,
    List_programs: null,
    List_defaultPromas: null,
    Macro_lis: null,
    Selected_port_com: null,
    GetDataNow: null,
    USER: null,
    PC: null,
    USERDATAUPDATE: {
        icon: null,
        name: null,
        username: null,
    },
};